"""unique version per scenario

Revision ID: f05679e1f472
Revises: 04b57f980045
Create Date: 2026-04-23 00:10:59.505665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05679e1f472'
down_revision: Union[str, Sequence[str], None] = '04b57f980045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_snapshots_scenario_version'), table_name='scenario_snapshots')
    op.create_unique_constraint('uq_scenario_snapshots_scenario_version', 'scenario_snapshots', ['scenario_id', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_scenario_snapshots_scenario_version', 'scenario_snapshots', type_='unique')
    op.create_index(op.f('ix_scenario_snapshots_scenario_version'), 'scenario_snapshots', ['scenario_id', 'version'], unique=False)
    # ### end Alembic commands ###
